set nocompatible              " be iMproved, required
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'tpope/vim-fugitive'
Plugin 'gmarik/Vundle.vim'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'bling/vim-airline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'chrisbra/csv.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'kien/ctrlp.vim'
Plugin 'fatih/vim-go'
call vundle#end()            " required
filetype plugin indent on    " required

autocmd FileType python set sw=3
autocmd FileType python set sw=3
autocmd FileType python set ts=3


set number
set smartindent
set expandtab

let g:ycm_collect_identifiers_from_tags_files = 1 " Let YCM read tags from Ctags file
let g:ycm_use_ultisnips_completer = 1 " Default 1, just ensure
let g:ycm_seed_identifiers_with_syntax = 1 " Completion for programming language's keyword
let g:ycm_complete_in_comments = 1 " Completion in comments
let g:ycm_complete_in_strings = 1 " Completion in string
let g:ycm_register_as_syntastic_checker = 0
let g:ycm_server_use_vim_stdout = 1
let g:ycm_server_log_level = 'debug'

" airline specific settings
set laststatus=2

let t_Co=256
"set term=xterm-color
let g:solarized_degrade = 0
set background=dark
colorscheme solarized
syntax on
let g:airline#extensions#tabline#enabled = 1

" start nerdtree on startup
" autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>
nmap <C-l> :TagbarToggle<CR>
map <C-i> :! ./manage.py shell_plus<CR>
"let g:syntastic_debug = 3

let g:syntastic_python_checkers=['flake8', 'pylint']
let g:syntastic_python_pylint_args = '--rcfile=~/.pylintrc'
"let g:syntastic_debug_file = '/tmp/syntastic.log'
" whitespace
"highlight ExtraWhitespace ctermbg=red
highlight ColorColumn ctermbg=red
call matchadd('ColorColumn', '\%82v', 100)
autocmd FileType py autocmd BufWritePre <buffer> StripWhitespace

" use system clipboard for yanking etc.,
set clipboard+=unnamed
